name: Publish to another (Prod) repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: HunterGerlach/nextjs-github-pages-multi-envs-prod
          path: ./
          token: ${{ secrets.REPO_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: root
          path: ./
          token: ${{ secrets.REPO_TOKEN }}
